<template>
  <button :class="color">
            <svg v-if="loading" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" style="margin: auto; background: none; display: block; shape-rendering: auto;" width="35px" height="30px" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid">
              <circle cx="84" cy="50" r="10" fill="#a2a2a2">
                <animate attributeName="r" repeatCount="indefinite" dur="0.5s" calcMode="spline" keyTimes="0;1" values="10;0" keySplines="0 0.5 0.5 1" begin="0s"/>
                <animate attributeName="fill" repeatCount="indefinite" dur="2s" calcMode="discrete" keyTimes="0;0.25;0.5;0.75;1" values="#a2a2a2;#fdfdfd;#8f8f8f;#dedede;#a2a2a2" begin="0s"/>
              </circle><circle cx="16" cy="50" r="10" fill="#a2a2a2">
              <animate attributeName="r" repeatCount="indefinite" dur="2s" calcMode="spline" keyTimes="0;0.25;0.5;0.75;1" values="0;0;10;10;10" keySplines="0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1" begin="0s"/>
              <animate attributeName="cx" repeatCount="indefinite" dur="2s" calcMode="spline" keyTimes="0;0.25;0.5;0.75;1" values="16;16;16;50;84" keySplines="0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1" begin="0s"/>
            </circle><circle cx="50" cy="50" r="10" fill="#dedede">
              <animate attributeName="r" repeatCount="indefinite" dur="2s" calcMode="spline" keyTimes="0;0.25;0.5;0.75;1" values="0;0;10;10;10" keySplines="0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1" begin="-0.5s"/>
              <animate attributeName="cx" repeatCount="indefinite" dur="2s" calcMode="spline" keyTimes="0;0.25;0.5;0.75;1" values="16;16;16;50;84" keySplines="0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1" begin="-0.5s"/>
            </circle><circle cx="84" cy="50" r="10" fill="#8f8f8f">
              <animate attributeName="r" repeatCount="indefinite" dur="2s" calcMode="spline" keyTimes="0;0.25;0.5;0.75;1" values="0;0;10;10;10" keySplines="0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1" begin="-1s"/>
              <animate attributeName="cx" repeatCount="indefinite" dur="2s" calcMode="spline" keyTimes="0;0.25;0.5;0.75;1" values="16;16;16;50;84" keySplines="0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1" begin="-1s"/>
            </circle><circle cx="16" cy="50" r="10" fill="#fdfdfd">
              <animate attributeName="r" repeatCount="indefinite" dur="2s" calcMode="spline" keyTimes="0;0.25;0.5;0.75;1" values="0;0;10;10;10" keySplines="0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1" begin="-1.5s"/>
              <animate attributeName="cx" repeatCount="indefinite" dur="2s" calcMode="spline" keyTimes="0;0.25;0.5;0.75;1" values="16;16;16;50;84" keySplines="0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1" begin="-1.5s"/>
            </circle>
              <!-- [ldio] generated by https://loading.io/ --></svg>
    <span v-else><searchIcon v-if="icon"/>{{ text }}</span>

  </button>
</template>

<script>
import searchIcon from "./searchIcon";

export default {
  name: "khoonegiButton",
  components: {
    searchIcon
  },
  props: {
    text: {
      require: true,
    },
    icon: {
      require: true,
    },
    color: {
      type: String,
      require: false,
      default: "slate",
    },
    loading: {
      type: Boolean,
      require: false,
    },
  },
};
</script>

<style lang="scss" scoped>
@import "../assets/scss/variables.scss";

button {
  font-weight: bold;
  border-radius: 7px;
  border: 1px solid transparent;
  padding: 0.5rem 2rem;
  font-size: 1em;
  box-shadow: 0px 0px 20px rgb(206 206 206 / 20%);

  span {
    display: flex;
    align-items: center;
    justify-content: center;
  }

  img {
    width: auto !important;
  }

  svg {
    margin-left: 10%;
  }

  &.slate {
    background-color: $main-khoonegi;
    color: #fff;
  }

  &.slate-not {
    background-color: #fff;
    color: $main-khoonegi;
    border: 1px solid $main-khoonegi;

    &:hover {
      background-color: $main-khoonegi;
      color: #fff;
      border-color: $main-khoonegi;
    }
  }

  &.failed {
    background-color: #fff;
    color: #ff2121;
    border-color: #ff2121;

    &:hover {
      cursor: pointer;
      background-color: #ff2121;
      color: #fff;
      border-color: #ff2121;
    }
  }

  &.slate-blur {
    background-color: #664ECA;
    color: #ffffff;
    border-color: #664ECA;
   &:hover {
    color: #ffffff;
    cursor: pointer;
    background-color: #8365ff;
    border-color: #8365ff;

  }
  }

  &.dark-slate {
    background-color: $dark-yellow;
    color: $text-white;
    border-color: $dark-yellow;

    &:hover {
      cursor: pointer;
      background-color: $text-white;
      color: $dark-yellow;
      border-color: $dark-yellow;
    }
  }

  &.dark-slate-reverse {
    background-color: $text-white;
    color: $dark-yellow;
    border-color: $dark-yellow;

    &:hover {
      cursor: pointer;
      background-color: $dark-yellow;
      color: $text-white;
      border-color: $dark-yellow;
    }
  }

  &.dark-bright-slate {
    background-color: $primary-yellow;
    color: #fff;
  }

  &.dark {
    background-color: $text-black;
    color: $text-white;
  }

  &.trans {
    background-color: transparent;
    color: $text-black;
  }

  &.disable {
    background-color: #6a44ff5c;
    color: $text-white;
  }

  &:hover {
    cursor: pointer;
    background-color: #fff;
    color: $main-khoonegi;
    border-color: $main-khoonegi;
  }

  @media only screen and (max-width: 480px) {
    font-size: 0.8em;
  }
}
</style>
